name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.0.0
      with:
        dotnet-version: '2.2.103' # SDK Version to use.
    - name: Install Powershell
      run: sudo apt-get install -y powershell
    - name: Install Android NDK
      env:
        ndkname: android-ndk-r20
      run: |
        echo "Downloading NDK"
        wget -q -O ndk.zip https://dl.google.com/android/repository/${ndkname}-linux-x86_64.zip
        echo "Extracting NDK"
        unzip -q ndk.zip -d .
        mv ${ndkname} ndk
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
        cd ndk
        pwd > ${GITHUB_WORKSPACE}/ndkpath.txt
        cd ${GITHUB_WORKSPACE}
        pwsh -Command ./patch.ps1
